### ISSUE TITLE
Brightness Issue

### ISSUE THREAD

**Issue by illvart** [fadlyas07/kernel_xiaomi_ugglite_sd425#1]
Hi, I'm a GreenForce lovers!
GreenForce ugglite still has a brightness bug that is too bright in position 0. Can you fix it?

**Comment by fadlyas07** [comment]
> Hi, I'm a GreenForce lovers!
> GreenForce ugglite still has a brightness bug that is too bright in position 0. Can you fix it?

**Comment by fadlyas07** [comment]
> Hi, I'm a GreenForce lovers!
> GreenForce ugglite still has a brightness bug that is too bright in position 0. Can you fix it?

https://github.com/fadlyas07/kernel_xiaomi_ugglite_sd425/commit/d7d86f11a8884e384744031185ecdf5434975263 :v
